apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: registro-atividades-2
resources:
- namespace.yaml
- postgres-pvc.yaml
- postgres-deployment.yaml
- postgres-service.yaml
- api-deployment.yaml
- api-service.yaml
images:
- name: tom-locatelli47/registro-star-wars-revolta-dos-clones-devops
  newTag: a88ce925cd359d441fed64c1d647f5baf5c559d4
- name: tomaslocatelli/registro-star-wars-revolta-dos-clones-devops
  newTag: latest
