[control_plane]
control-plane ansible_host=54.173.27.32 private_ip=172.31.63.210

[workers]
worker-1 ansible_host=3.236.183.147 private_ip=172.31.12.12
worker-2 ansible_host=35.174.7.134 private_ip=172.31.28.195
worker-3 ansible_host=98.80.217.233 private_ip=172.31.71.52

[k8s_nodes:children]
control_plane
workers

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/labsuser.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'